# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: SNAPSHOT Build

on:
  push:
    branches: [ master ]

jobs:
  linux:
    if: "!contains(github.event.head_commit.message, 'cd skip')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup AdoptOpenJDK 14
      uses: joschi/setup-jdk@v2.3.0
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build JAR dist files
      run: ./gradlew dist
    - name: Build deb package
      run: ./gradlew jpackage
    - name: Fix deb file names
      run: mv build/jpackage/*.deb HyperLap2D-SNAPSHOT.deb
    - name: Upload deb artifact
      uses: actions/upload-artifact@v2
      with:
        name: HyperLap2D-SNAPSHOT.deb
        path: HyperLap2D-SNAPSHOT.deb
    - name: Publish SNAPSHOT artifacts
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: ./gradlew uploadArchives -PSNAPSHOT=true

  windows:
    if: "!contains(github.event.head_commit.message, 'cd skip')"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup AdoptOpenJDK 14
      uses: joschi/setup-jdk@v2.3.0
      with:
        java-version: 14
    - name: Build JAR dist files
      run: ./gradlew.bat dist
    - name: Build msi package
      run: ./gradlew.bat jpackage
    - name: Fix file names
      run: mv build/jpackage/*.msi HyperLap2D-SNAPSHOT.msi
    - name: Upload msi artifact
      uses: actions/upload-artifact@v2
      with:
        name: HyperLap2D-SNAPSHOT.msi
        path: HyperLap2D-SNAPSHOT.msi

  macOS:
    if: "!contains(github.event.head_commit.message, 'cd skip')"
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup AdoptOpenJDK 14
      uses: joschi/setup-jdk@v2.3.0
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build JAR dist files
      run: ./gradlew dist
    - name: Build dmg package
      run: ./gradlew jpackage
    - name: Fix file names
      run: mv build/jpackage/*.dmg HyperLap2D-SNAPSHOT.dmg
    - name: Upload dmg artifact
      uses: actions/upload-artifact@v2
      with:
        name: HyperLap2D-SNAPSHOT.dmg
        path: HyperLap2D-SNAPSHOT.dmg
